language: node_js

services:
  - mysql

node_js:
  - "stable"

before_install:
  - cd ./db/
  - mysql -e 'source ./db_setup.sql;'
  - cd ../

script:
  - cd ./client
  - npm install
  - npm test
  - npm run build

  - cd ../api
  - npm install
  - node hashPws.js
  - mocha test/
  - npm run start & 