language: node_js

services:
  - mysql

node_js:
  - "stable"

script:

  - cd ./client
  - npm install
  - npm test
  - npm run build

  - cd ../api
  - npm install
  - mocha test/
  - npm run start & 